apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello Kubernetes!</title>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300">
      To embed the CSS directly in the HTML using a style tag, you can modify your ConfigMap like this:
yamlCopyapiVersion: v1
kind: ConfigMap
metadata:
  name: app3-resources
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello Kubernetes!</title>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300">
      <style>
        body {
          font-family: 'Ubuntu', sans-serif;
          background-color: #eff7ff;
          margin: 0;
          padding: 20px;
        }
        .main {
          max-width: 800px;
          margin: 0 auto;
          background: white;
          padding: 20px;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.05);
          text-align: center;
        }
        .content {
          margin: 20px 0;
        }
        #message {
          font-size: 24px;
          margin: 20px 0;
        }
        #info {
          margin-top: 30px;
        }
        table {
          margin: 0 auto;
          border-collapse: collapse;
        }
        th, td {
          padding: 8px 15px;
          text-align: left;
          border-bottom: 1px solid #ddd;
        }
        th {
          font-weight: bold;
        }
      </style>
    </head>
    <body>
      <div class="main">
        <img src="https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg"/>
        <div class="content">
          <div id="message">
            Hello from app1.
          </div>
        </div>
        <div id="info">
          <table>
            <tr>
              <th>pod:</th>
              <td id="pod">Loading...</td>
            </tr>
            <tr>
              <th>node:</th>
              <td id="node">Loading...</td>
            </tr>
          </table>
        </div>
      </div>
    </body>
    </html>
