Vagrant.configure("2") do | config |

  config.vm.box = "bento/debian-11"
  
  config.vm.synced_folder "./confs", "/home/vagrant/confs"

  config.vm.define 'obelkhadS' do |server|
    server.vm.hostname = 'obelkhadS'
    server.vm.network 'private_network', ip: '192.168.56.110'
   
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      vb.cpus = 1
      vb.memory = 1024

    end
    server.vm.provision "shell", path: "scripts/init.sh"
    server.vm.provision "shell", path: "scripts/apply.sh"
  end

end