# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  config.vm.define 'obelkhadS' do |server|
    server.vm.hostname = 'obelkhadS'
    server.vm.network 'private_network', ip: '192.168.56.110'
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      vb.name = "obelkhad_S"
      vb.cpus = 1
      vb.memory = 1024

    end
    server.vm.provision "shell", path: "scripts/masterNode.sh"
  end

  config.vm.define 'obelkhadSW' do |worker|

    worker.vm.hostname = 'obelkhadSW'
    worker.vm.network 'private_network', ip: '192.168.56.111'
    worker.vm.provider 'virtualbox' do |vb|
      vb.name = "obelkhad_SW"
      vb.cpus = 1
      vb.memory = 1024
    end

    worker.vm.provision "shell", path: "scripts/workerNode.sh"
  end
end
