apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: css-volume
          mountPath: /usr/share/nginx/html/css/main.css
          subPath: main.css
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: html-volume
        configMap:
          name: app1-resources
          items:
          - key: index.html
            path: index.html
      - name: css-volume
        configMap:
          name: app1-resources
          items:
          - key: main.css
            path: main.css
      - name: config-volume
        configMap:
          name: app1-resources
          items:
          - key: default.conf
            path: default.conf
